exclude_path = [
    "file://.*?\\.\\.\\./",
    "https://github.com/healpy/healpy/blob/main/CHANGELOG.rst",
    "https://github.com/healpy/healpy/issues",
    "https://github.com/zonca/zonca.dev/edit/main/posts/.*",
    "https://help.openai.com/en/articles/10193193-1-800-chatgpt-calling-and-messaging-chatgpt-with-your-phone",
    "https://chatgpt.com/",
    "http://zeus.nyf.hu/~blahota/maxima/karmic/",
    "http://showmedo.com/videotutorials/series?name=N49qyIFOh",
    "https://www.udacity.com/courses#!/data-science",
    "http://www.hdfgroup.org/HDF5-FAQ.html#gcite",
    "http://cxc.harvard.edu/mta/ASPECT/tool_doc/pydocs/Quaternion.html",
    "http://www.w3schools.com/xsl",
    "http://healpix.jpl.nasa.gov/",
    "http://www.enthought.com/products/edudownload.php",
    "https://www.xsede.org/for-users/ecss",
    "https://tacc.jetstream-cloud.org/dashboard",
    "https://github.com/ged-lab",
    "https://github.com/organizations/new",
    "https://blink.ucsd.edu/technology/security/services/two-step-login/guide.html#token",
    "https://www.yubico.com/products/yubikey-hardware/",
    "https://zonca.dev/2020/05/kubernetes-jupyterhub-jetstream-magnum.html",
    "https://zonca.dev/2020/06/kubernetes-jetstream-kubespray.html",
    "http://www.sdsc.edu/services/it/cloud.html",
    "http://www.sdsc.edu/us/resources/gordon/",
    "http://www.sdsc.edu/us/resources/gordon/gordon_hadoop.html",
    "https://singularityhub.github.io/singularity-registry/inst/",
    "https://portal.xsede.org/allocations/research",
    "https://iujetstream.atlassian.net/wiki/spaces/JWT/pages/39682057/Using+the+Jetstream+API",
    "https://portal.xsede.org/allocations/startup#trial",
    "https://portal.xsede.org/allocations/startup",
    "http://www.sdsc.edu/services/it/colocation.html",
    "http://authors.acm.org/main.html",
    "https://pangeo.pydata.org/",
    "http://code.shutterstock.com/rickshaw/",
    "http://www.nersc.gov/users/data-analytics/data-analytics-2/jupyter-and-rstudio/",
    "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet",
    "https://www.sdsc.edu/Events/training/webinars/distributed_parallel_computing_with_python_2019/recording/",
    "http://www.sdsc.edu/services/hpc/tscc-purchase.html",
    "http://www.sdsc.edu/collaborate/hpc_at_uc.html"
]
