name: Render and Publish Quarto Project

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.6.43'

      - name: Install dependencies
        run: |
          npm install

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Render Quarto Project (PRs)
        if: github.event_name == 'pull_request'
        run: make render

      - name: Render and Publish Quarto Project (Main Branch)
        if: github.event_name != 'pull_request'
        run: make all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --base '${{ github.workspace }}/_site'
            --no-progress
            --exclude-path 'file://.*?\.\./'
            --exclude 'https://github.com/healpy/healpy/blob/main/CHANGELOG.rst'
            --exclude 'https://github.com/healpy/healpy/issues'
            --exclude 'https://github.com/zonca/zonca.dev/edit/main/posts/.*'
            --exclude 'https://help.openai.com/en/articles/10193193-1-800-chatgpt-calling-and-messaging-chatgpt-with-your-phone'
            --exclude 'https://chatgpt.com/'
            --exclude 'http://zeus.nyf.hu/~blahota/maxima/karmic/'
            --exclude 'http://showmedo.com/videotutorials/series?name=N49qyIFOh'
            --exclude 'https://www.udacity.com/courses#!/data-science'
            --exclude 'http://www.hdfgroup.org/HDF5-FAQ.html#gcite'
            --exclude 'http://cxc.harvard.edu/mta/ASPECT/tool_doc/pydocs/Quaternion.html'
            --exclude 'http://www.w3schools.com/xsl'
            --exclude 'http://healpix.jpl.nasa.gov/'
            --exclude 'http://www.enthought.com/products/edudownload.php'
            --exclude 'https://www.xsede.org/for-users/ecss'
            --exclude 'https://tacc.jetstream-cloud.org/dashboard'
            --exclude 'https://github.com/ged-lab'
            --exclude 'https://github.com/organizations/new'
            --exclude 'https://blink.ucsd.edu/technology/security/services/two-step-login/guide.html#token'
            --exclude 'https://www.yubico.com/products/yubikey-hardware/'
            --exclude 'https://zonca.dev/2020/05/kubernetes-jupyterhub-jetstream-magnum.html'
            --exclude 'https://zonca.dev/2020/06/kubernetes-jetstream-kubespray.html'
            --exclude 'http://www.sdsc.edu/services/it/cloud.html'
            --exclude 'http://www.sdsc.edu/us/resources/gordon/'
            --exclude 'http://www.sdsc.edu/us/resources/gordon/gordon_hadoop.html'
            --exclude 'https://singularityhub.github.io/singularity-registry/inst/'
            --exclude 'https://portal.xsede.org/allocations/research'
            --exclude 'https://iujetstream.atlassian.net/wiki/spaces/JWT/pages/39682057/Using+the+Jetstream+API'
            --exclude 'https://portal.xsede.org/allocations/startup#trial'
            --exclude 'https://portal.xsede.org/allocations/startup'
            --exclude 'http://www.sdsc.edu/services/it/colocation.html'
            --exclude 'http://authors.acm.org/main.html'
            --exclude 'https://pangeo.pydata.org/'
            --exclude 'http://code.shutterstock.com/rickshaw/'
            --exclude 'http://www.nersc.gov/users/data-analytics/data-analytics-2/jupyter-and-rstudio/'
            --exclude 'https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'
            --exclude 'https://www.sdsc.edu/Events/training/webinars/distributed_parallel_computing_with_python_2019/recording/'
            --exclude 'http://www.sdsc.edu/services/hpc/tscc-purchase.html'
            --exclude 'http://www.sdsc.edu/collaborate/hpc_at_uc.html'
            '_site/**/*.html'
          fail: true

